### ISSUE TITLE
placeholder tag error

### ISSUE THREAD

**Issue by rikardfroberg** [projectestac/odissea#13]
Hi!
In odissea/html/moodle2/langpacks/sv/message.php there is a typo in the placeholder tag for sitename.

It says Det här e-postmeddelandet är en kopia av ett meddelande som har skickats till Dig på "{$a>sitename}".

When it should say:
Det här e-postmeddelandet är en kopia av ett meddelande som har skickats till Dig på "{$a->sitename}".

The difference is in the tag. Replace {$a>sitename} with {$a->sitename} and it should work.

The missing dash makes the placeholder not expand.

**Comment by sarjona** [comment]
Hi @rikardfroberg !!

We've sent the new string to the official Moodle translation page: https://lang.moodle.org/local/amos/view.php

Thanks for helping us to improve it!! :-)
