### ISSUE TITLE
Millorar el works.php per comprovar també el Moodle 2

### ISSUE THREAD

**Issue by sarjona** [projectestac/odissea#7]
El works.php actual només comprova la instància del Moodle 1.9. Cal millorar-lo per validar també la del Moodle 2.

Valorar la possibilitat de moure les dades d'accés a les bases de dades des del config dels dos Moodles a html/config/ utilitzant els mateixos fitxers i variables que a Àgora.

**Comment by crazyserver** [comment]
@sarjona diria que això, o bé ja està fet o bé es pot tancar perquè no aplica...

**Comment by sarjona** [comment]
@crazyserver Perfecte! :+1:  Una cosa menys doncs! :-)
