### ISSUE TITLE
Convertir els camps CLOB a VARCHAR2 al Moodle 2

### ISSUE THREAD

**Issue by sarjona** [projectestac/odissea#8]
En el Moodle 2, a les taules config i config_plugins, convertir el camp "value" de CLOB a VARCHAR2 per tal de millorar el rendiment del Moodle 2.

**Comment by toniginard** [comment]
Quan es faci la migració a AWS passarem d'Oracle a Postgres. Per aquest motiu, aquest canvi no es farà.
